// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6w5gj_wqbvpc3L-EFtaztIsveKzH3CV8',
    appId: '1:669365271986:web:22372f2f3de2db0424b8ab',
    messagingSenderId: '669365271986',
    projectId: 'firestorenotes-80a8e',
    authDomain: 'firestorenotes-80a8e.firebaseapp.com',
    storageBucket: 'firestorenotes-80a8e.appspot.com',
    measurementId: 'G-XW30052PJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWGRW767KGJwjfn7YxGGI2cQMNqag2Q0',
    appId: '1:669365271986:android:afa79a3bd2c3ca0724b8ab',
    messagingSenderId: '669365271986',
    projectId: 'firestorenotes-80a8e',
    storageBucket: 'firestorenotes-80a8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM2N7SPDLJV2cKjn8g0Um9EirIByA3sxs',
    appId: '1:669365271986:ios:860fd4f3124b489324b8ab',
    messagingSenderId: '669365271986',
    projectId: 'firestorenotes-80a8e',
    storageBucket: 'firestorenotes-80a8e.appspot.com',
    iosBundleId: 'com.example.firestoreNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM2N7SPDLJV2cKjn8g0Um9EirIByA3sxs',
    appId: '1:669365271986:ios:a8d2a6bc4459e3b024b8ab',
    messagingSenderId: '669365271986',
    projectId: 'firestorenotes-80a8e',
    storageBucket: 'firestorenotes-80a8e.appspot.com',
    iosBundleId: 'com.example.firestoreNotes.RunnerTests',
  );
}
